### PR TITLE
Added option to auto-balance teams at end of map.

### PR DESCRIPTION
**Pull request by xia0**

### CODE REVIEW

**Comment by ScureX** [comment]
Hey, thank you for contributing! I really like what you've done so I will merge this as soon as possible, so I only have a few Questions:

- Have you tested this new feature?
- Why did you revert the changes done to ```takyon_help.nut```?

**Review by ScureX — APPROVED** [review]

**Comment by xia0** [comment]
hey dude thanks for approving my pr. the help file i wanted to fix up by not showing the commands that were not enabled but felt it was outside the scope of this PR so i left it the way it was. im keen to work on your mod more if you're open to that.

**Comment by xia0** [comment]
i have indeed tested it btw. wouldnt pr to main if I hadn't.

**Comment by ScureX** [comment]
Your PR has already been released together with some hotfixes in v3.0.1! I'm split with what you did with the help file, kinda like it, kinda dont :P We'll see maybe it can be a future feature or toggleable. 
Since this mod is getting kinda big I'd love to see more from you! I'm currently working on rewriting it to make some things more streamlined which will then be released in v4.0.0, so keep that in mind and maybe ask before you add something that relies on other features! 
For features either look [here](https://github.com/ScureX/Takyon.PlayerVote/projects/1) to see what i have planned, look [here](https://github.com/ScureX/Takyon.PlayerVote/discussions) to see what others have suggested or suggest something yourself. 
Again, thank you for contributing to this project :D

**Pull request merged**
